# Default Theme Configuration

orientation = "landscape"
refresh = "redraw"

[[screens]]
id = 1
name = "Main"
background = "#000000"
duration = 0

[[screens.widgets]]
id = 1
name = "text"
value = "HT32 Panel"
[screens.widgets.rect]
x = 100
y = 70
width = 120
height = 30
